curl -X POST --header "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x7557ed53Ef126777027f34a8B6cCc987B1be9077","latest"],"id":1}' https://testetscrpc.digifinex.org/