curl --user Xd3W5tRHsiW5GYZ:dCsgw8VB7sN5hhi --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "listunspent", "params": [1, 9999999, ["DSw97BdqSeFQrviQ5553AJNqaBneuYiSbC"],2] }'  https://testddrrpc.digifinex.org/ | jq
