curl --user main:main --data-binary '{"jsonrpc":"1.0","id":"curltest","method":"importaddress","params":[""]}' http://dns.seed2.latinum.staking.zeeve.net:38555/wallet/tsswallet  | jq
http://main:main@dns.seed2.latinum.staking.zeeve.net:38555/wallet/testwallet/
