curl --user iqlas@cumuluslogic.net:test --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "sendtoaddress", "params": ["xMEPz3bYeh4fQjhntmQ1hP4Q4GMPx5dpv6",200] }'  http://18.169.65.221:38552/wallet/ | jq