
# ctrl + alt + r   // send request
# ctrl + alt + m   // open json
# alt + m mini     // json

#UserName
@UserName = ca72UzFyRHkpdd7R
#PassWord
@PassWord = Gq8rjgT2XdtyTg4J
#Node
@Node = https://testarrrrpc.digifinex.org