

curl --user ca72UzFyRHkpdd7R:Gq8rjgT2XdtyTg4J --data-binary '{"jsonrpc":"1.0","id":"curl","method":"z_validateaddress","params":["zs1uffcfr8t9ynpe9xjvs4gxq2hunkmrqf7zzhjlh7ryr3aqnjncfyvveus40z9rfrd82qczjnfpa9"]}' https://testarrrrpc.digifinex.org | jq