curl --user ca72UzFyRHkpdd7R:Gq8rjgT2XdtyTg4J --data-binary '{"jsonrpc":"1.0","id":"curl","method":"getblock","params":["00000000062c80a2182f16983c47ab7671c1ccc027cfe27f5d5cce3b257b214d",2]}' https://arrrpushrpc.digifinex.org/ 