
curl --user ca72UzFyRHkpdd7R:Gq8rjgT2XdtyTg4J --data-binary 
'
{
    "jsonrpc": "1.0",
    "id": "curl",
    "method": "sendtoaddress",
    "params": [
        "zs147yu3v03nj0lkzxfd4jxy5dgmdu40fl6tkdmn2qylljcetm0w5jmn3l53y9cu3mnhj27v0vx63y",
        0.001,
        "test transfer",
        "test transfer send to zhangfei "
    ]
}
' 
https://testarrrrpc.digifinex.org/ | jq