curl --user ca72UzFyRHkpdd7R:Gq8rjgT2XdtyTg4J --data-binary '{"jsonrpc":"1.0","id":"curl","method":"z_getoperationstatus","params":[["opid-6aadd9b8-debc-4044-b075-4389b07f2149"]]}' https://arrrpushrpc.digifinex.org/ 