curl --user ca72UzFyRHkpdd7R:Gq8rjgT2XdtyTg4J --data-binary 
'
{
    "jsonrpc": "1.0",
    "id": "curl",
    "method": "zs_listreceivedbyaddress",
    "params": [
        "zs1h3qv3pcqw6m7y50x7tkcuf8d95lun6cxzmc2geuqldqhm0y88hk8fyqzg2flu5rzyj9fcs5m5t7"
    ]
}
' 
https://testarrrrpc.digifinex.org/ | jq`